### ISSUE TITLE
Today 404 on http://bit.ly/coolstore-ansible-template

### ISSUE THREAD

**Issue by tombolala** [siamaksade/openshift-demos-ansible#6]
Hi,

don't know if that is a temporary problem, but the URL described does not work today and results in 404.
http://bit.ly/coolstore-ansible-template -> https://raw.githubusercontent.com/siamaksade/openshift-demos-ansible/master/helpers/coolstore-ansible-installer.yaml
404

Thanx,
Thomas

**Comment by siamaksade** [comment]
Updated docs d6c80cd82756c965fbeb4abfb06a426d0cbddc15
